### ISSUE TITLE
Remove attribute and index from Ohm::Model causing NoMethodError: undefined method (removed attribute) when load model

### ISSUE THREAD

**Issue by phuongnd08** [soveran/ohm#167]
I have an Ohm::Model that define an attribute and an index.
When I later remove the attribute, and try to load the model, it's say: `NoMethodError: undefined method <removed_attribute_name>`.

**Comment by hackeron** [comment]
I've removed an attribute from my model and I'm getting the dreaded:

```
NoMethodError: undefined method `live_token=' for #<User:0x0000000641ca98>
```

Is there anyway to remove this live_token attribute from the database without rewriting my model file?

Something live the above User.all.remove_attribute(: live_token) would be fantastic, but can't seem to find anything like this.

**Comment by jogaco** [comment]
Is it possible to drop all redis information for a given class, so that if I reinsert, it starts assigning ids from 1?

A command such as

```
Post.destroy
```
to delete all Post metadata stored at redis would be useful.
