### ISSUE TITLE
Ohm upgrade - finding records with non-set attributes

### ISSUE THREAD

**Issue by gingerlime** [soveran/ohm#171]
I'm in the process of upgrading to Ohm 2 and have encountered a change in behaviour that I'm not entirely sure how to work around.

Before, I could filter for non-set indexed attributes by searching for `nil`. Now it seems not to work any more...

```ruby
class Post < Ohm::Model
  attribute :published
  index :published
end

p1 = Post.create
p2 = Post.create(published: true)
# Before
Post.all.except(published: nil).size # => 1
# Now
Post.all.except(published: nil).size # => 2
```

Any suggestions on how to filter non-set attributes with the latest Ohm version?

**Comment by soveran** [comment]
@gingerlime I released an update to the 1.3 branch (version 1.4 is out and includes a new filter type, `combine`). I'm closing this issue as we can't fix it easily (it's a backwards incompatible change), but I will keep maintaining the 1.4.x branch.

**Comment by gingerlime** [comment]
Thanks for the update @soveran. We eventually decided to move away from Ohm. We just couldn't upgrade safely to 2.0 and some things felt like they didn't really fit for us.

**Comment by soveran** [comment]
No problem!
