### ISSUE TITLE
synchronize in sort_by causes hanging in multithreaded environment?

### ISSUE THREAD

**Issue by kosh-jelly** [soveran/ohm#176]
I'm using ohm with sidekiq and after 15 - 24 hours sidekiq constantly hangs. About 90% of the 200 threads are stuck on this:

/app/vendor/bundle/ruby/2.1.0/gems/ohm-2.0.1/lib/ohm.rb:782:in `synchronize'
/app/vendor/bundle/ruby/2.1.0/gems/ohm-2.0.1/lib/ohm.rb:782:in `synchronize'
/app/vendor/bundle/ruby/2.1.0/gems/ohm-2.0.1/lib/ohm.rb:139:in `fetch'
/app/vendor/bundle/ruby/2.1.0/gems/ohm-2.0.1/lib/ohm.rb:376:in `sort'
/app/vendor/bundle/ruby/2.1.0/gems/ohm-2.0.1/lib/ohm.rb:344:in `sort_by'

The line in my code that calls sort_by is using a 1-to-many relationship: live_domain.queued_pages.sort_by(:page_depth, :order => "DESC", :limit => [0,1]).first

Does sort_by not work in a multi-threaded environment? Or am I implementing it wrong?

I'm also noticing serious memory bloat in my sidekiq instances which could be a related problem if all the queued_page objects are being loaded into memory...

**Comment by soveran** [comment]
@kosh-jelly It looks like it may be a problem with Timeout in Ruby 2.1.0. Can you check if you get the errors only with that version?

**Comment by soveran** [comment]
@kosh-jelly I'm closing this now, but please reopen it if you encounter any issues. Thanks a lot for this report.
