### ISSUE TITLE
Calling collection attribute is returning string instead of collection

### ISSUE THREAD

**Issue by barberj** [soveran/ohm#185]
```
NoMethodError: undefined method `each_slice' for "123276":String
```

class SomeClass < Ohm::Model
  collection :children, :SomeClass, :parent
end

x = SomeClass.new
x.children.map { |c| c.id }

Running in a multithreaded environment under sidekiq. Having troubles reproducing locally.

From `lib/ohm.rb`
```
 113   module Collection
 114     include Enumerable
 115
 116     def each
 117       if block_given?
 118         ids.each_slice(1000) do |slice|
 119           fetch(slice).each { |e| yield(e) }
 120         end
 121       else
 122         to_enum
 123       end
 124     end
```

**Comment by soveran** [comment]
@barberj Could it be related to this issue? https://github.com/redis/redis-rb/issues/501

Which Ruby version are you running in prod?

**Comment by barberj** [comment]
ruby 2.0. I ended up rolling my own home grown redis models since could never get ohm to work.

**Comment by soveran** [comment]
Can you share some piece of code so that I can try to reproduce it?

**Comment by soveran** [comment]
Closing this as we don't have a way to replicate the issue.
