### ISSUE TITLE
attribute default value contribution 

### ISSUE THREAD

**Issue by b-murphy** [soveran/ohm#191]
Hey Soveran & folks :-)

I've been working on a project using Ohm, currently and have come to the point where i will need to define default values for attributes on my objects.

So my question isn't the possibility of it, more of where / if  it would be welcomed as an addition? Considering that ohm-contrib does not mutate ohm in any way (i can see..!) This addition would re-open the attribute singleton method, would it be suitable to PR to the core?

Perhaps this added too much complexity for a simple objectives of ohm, but i thought i'd ask!

**Comment by soveran** [comment]
Hey there! I think there are probably two ways to mimic that behavior. One would be to use [callbacks](https://github.com/cyx/ohm-contrib#on-the-topic-of-callbacks) and set the default value, and the other would be to use attribute casting:

```ruby
class Foo < Ohm::Model
  attribute :bar, ->(value) { value || "default" }
end

assert_equal "default", Foo.new.bar #=> true
```
Would that work for your use case?

**Comment by soveran** [comment]
Closing this for now, please let me know if we should reopen it.
