### ISSUE TITLE
Unable to save model

### ISSUE THREAD

**Issue by deric** [soveran/ohm#192]
When I try to save a model, I get this error:

```
Redis::CommandError: ERR unknown command 'url'
redis-3.2.1/lib/redis/client.rb:113:in `call'
redis-3.2.1/lib/redis.rb:2556:in `block in method_missing'
redis-3.2.1/lib/redis.rb:37:in `block in synchronize'
monitor.rb:211:in `mon_synchronize'
redis-3.2.1/lib/redis.rb:37:in `synchronize'
redis-3.2.1/lib/redis.rb:2555:in `method_missing'
ohm-2.2.0/lib/ohm.rb:1349:in `script'
ohm.rb:1302:in `save'
```
The problem seems to be [here](https://github.com/soveran/ohm/blob/0c385ae53b2b79e3b9f555d077f72ffaebd2e0aa/lib/ohm.rb#L1467)

the call `redis.url` is causing method missing error, probably it should be something like `redis.client.options.url`
```
    # Run lua scripts and cache the sha in order to improve
    # successive calls.
    def script(file, *args)
      cache = LUA_CACHE[redis.url]

      if cache.key?(file)
        sha = cache[file]
      else
        src = File.read(file)
        sha = redis.call("SCRIPT", "LOAD", src)

        cache[file] = sha
      end

      redis.call("EVALSHA", sha, *args)
    end
```

However, the `url` doesn't have to be defined at all. What if the client is connected via an UNIX socket?

**Comment by frodsan** [comment]
Ohm 2.0 only supports [Redic](https://github.com/amakawa/redic). I guess you are using `redis-rb`.

See: https://github.com/soveran/ohm#connecting-to-a-redis-database

**Comment by deric** [comment]
You're right, I've totally overlooked that. Thanks!
