### ISSUE TITLE
How to remove an attribute from an ohm model?

### ISSUE THREAD

**Issue by hackeron** [soveran/ohm#199]
I edited my Ohm model file to remove an attribute that is no longer required. When I try to fetch the first item, I get:

```ruby
agent(prod)> User.all.first
NoMethodError: undefined method `live_token=' for #<User:0x0000000658f128>
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:1382:in `block in update_attributes'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:1382:in `each'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:1382:in `update_attributes'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:1098:in `initialize'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:150:in `new'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:150:in `block (2 levels) in fetch'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:149:in `each'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:149:in `each_with_index'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:149:in `block in fetch'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:148:in `tap'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:148:in `fetch'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:452:in `sort'
	from /var/lib/gems/2.0.0/gems/ohm-2.2.0/lib/ohm.rb:493:in `first'
	from (irb):40
	from /var/lib/gems/2.0.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /var/lib/gems/2.0.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /var/lib/gems/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /var/lib/gems/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /var/lib/gems/2.0.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

How do I do a type of migration to remove this no longer requires live_token attribute?

I found a few suggestions like #70 and http://stackoverflow.com/questions/12138278/ohm-how-to-drop-a-column-attribute but it seems the information there no longer applies in the latest version.

**Comment by soveran** [comment]
What's happening is that in the database, the field `live_token` still exists, so the best way to deal with that is to first set all those fields to `nil`, and just then remove the attribute from the code. The way to fix it now is a bit more complex, but totally feasable.

First, remember that if you load any `User`, you will get that error, so iterating on `User.all` won't work. But you can access the user ids, and iterate on them. Try the following code:

```ruby
User.all.ids.each do |id|
  User.redis.call("HDEL", User.key[id], "live_token")
end
```

That should remove all the live token fields from the database, and loading the users will work again. If you have indices or any other relevant declarations in your `User` model, let me know and we'll figure out what to do.

**Comment by hackeron** [comment]
Thank you for the feedback, that works :) - I ended up doing this in a temporary initialiser file:

```ruby
begin
  User.all.first
rescue
  User.all.ids.each do |id|
    User.redis.call("HDEL", User.key[id], "live_token")
    User.redis.call("HDEL", User.key[id], "event_token")
  end
end
```

Seems a bit messy - I prefer how Mongoid deals with adding/removing fields but thank you for the solution :)

**Comment by soveran** [comment]
Yes, it's true that it doesn't look very elegant, sorry for that. The best way to handle it for now is to set those fields to null first, and then you can change the code directly without running those direct calls to Redis.

**Comment by hackeron** [comment]
I am deploying this code with Ansible to hundreds of servers - some of them have this field, some do not. Essentially I want to just ignore any fields that I no longer care about.

It seems like a lot of extra steps to to set those fields to null? E.g.
1. Copy an extra script to the server before updating the source
2. Run this script with bundle exec
3. This script will check for the existence of these methods/fields
4. If these methods/fields exist, it will set values to null
5. Update source and continue normal deploy

Seems even less elegant and a lot of extra work. Unless I'm missing something?

**Comment by soveran** [comment]
I think we can split the problem in two: one problem is the migration, and the other is the fact that in your case, some servers had the extra fields and some didn't. The later is probably a very particular case that is not worth generalizing, and we can focus on the first problem instead.

In the general case, the benefit of setting the fields to null is that if there are any indices, they will be updated to remove any references to that field.

As the code dictactes what the meaning is for the data in Redis, having a migration script may be our only option here. We could consider the addition of a migration feature, something that would allow us to write a script with instructions like `User.remove_attribute(:foo)`, but despite the fact that it should be very carefully designed, it means we won't be able to skip the migration step. As having a migration step to modify the database structure is a common pattern, I think it makes sense to at least copy to the documentation what we have discussed here.

**Comment by hackeron** [comment]
That would be fantastic! - Right now it's a kind of a chicken and egg situation: in order to set to null, I need to git pull and run the new code, but if I do that, Ohm becomes unusable as the attribute is missing in the model.

So something like User.remove_attribute(:foo) would be great :) - maybe that can return the attribute name if exists and nil if it is already removed (with another remove_attribute! method that will raise an exception if attribute is missing).
