### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by u2** [soveran/ohm#205]
Does ohm support transaction? And how to do if I want to write some transaction, any recommend method?

**Comment by soveran** [comment]
Hello @u2, there was a way to compose transactions in Ohm 1.x, but starting with Ohm 2 the transaction happens directly in the Lua script. Can you tell me more about your use case? Maybe we can figure out something.

**Comment by u2** [comment]
I just want something like this:
```ruby
Ohm::Transaction do
  AttestationVolume.create(product_id: 1, date: date)
  AttestationVolume.create(product_id: 2, date: date)
 AttestationVolume.create(product_id: 3, date: date)
end
```
But I find that the Ohm::Model#transaction and Ohm::Transaction have been removed.

**Comment by soveran** [comment]
Yes, it was removed for version 2. But version 1 is still maintained, you can use it safely. The latest release is [1.4.0](https://github.com/soveran/ohm/releases/tag/1.4.0). Just as a side note, there are many users of 1.4.0 out there, so you won't be alone :-)

I will close this issue for now, let me know if it works for you.
