### ISSUE TITLE
Redis Sentinel support

### ISSUE THREAD

**Issue by scalp42** [soveran/ohm#217]
Just like , I noticed that the underlying client does not support Sentinel (I discovered this too late unfortunately).

Not sure if redis-rb code could help: https://github.com/redis/redis-rb#sentinel-support

Also I'm not sure if I should open an issue here or in redic.

Any pointers would be much appreciated 🍶

**Comment by soveran** [comment]
@scalp42 I'm tinkering with something related, I will update you soon :-)

**Comment by scalp42** [comment]
@soveran amazing news and great timing 😅

**Comment by scalp42** [comment]
Not trying to be pushy but really wondering you have any updates 😇  @soveran 

ping @arnaud036 also

**Comment by soveran** [comment]
Hey @scalp42, sorry for the delay. I have something that may be ready for you to try. I'll finish it and upload it today, and I'll ping you once it's up.

**Comment by scalp42** [comment]
Again no worries at all, I'm not expecting anything to be clear (but would definitely ease a lot of issues) and thank you for all the work with Ohm in general!

**Comment by soveran** [comment]
@scalp42 I just pushed an alpha version of [Redisent](https://rubygems.org/gems/redisent) (code [here](https://github.com/soveran/redisent)). I have to try it more with Ohm, and make sure it works perfectly. I'll dedicate time to it in the following days and I'll update you if I make any progress.

**Comment by soveran** [comment]
This should be available in Redisent 0.1.0.
