### ISSUE TITLE
Search by part

### ISSUE THREAD

**Issue by alexey** [soveran/ohm#230]
Hello, 

I am trying to implement search that match part of value, for example:
`set = MyOhmModel.find name: 'Alexe'`

I tried to use `.combine` and `.union` methods and the `*` at the end of searched value, but no luck getting results that match part of string..
Is this something doable ?

**Comment by soveran** [comment]
Partial matches are not doable unless you create an index, but such index would probably use a lot of memory. My advice would be to use something else for full text search with partial matches. You can still use Ohm, but you would keep a full text search index somewhere else.
