### ISSUE TITLE
Ohm on Windows

### ISSUE THREAD

**Issue by lynnfaraday** [soveran/ohm#236]
Using Ohm 3.1.1.

I was attempting to get a project running with Ruby on Windows, and Ohm is having trouble accessing the database.   The error is `A non-blocking socket operation could not be completed immediately. - read would block`.  

This happens on all calls, as demonstrated by the simple 'set' from the example:

```
irb(main):001:0> require 'ohm'
WARNING: could not load hiredis extension, using (slower) pure Ruby implementation.
=> true
irb(main):002:0> Ohm.redis = Redic.new("redis://127.0.0.1:6379")
=> #<Redic:0x00000000038617f0 @url="redis://127.0.0.1:6379", @client=#<Redic::Client:0x00000000038617c8 @semaphore=#<Thread::Mutex:0x00000000038617a0>, @connection=false, @uri=#<URI::Generic redis://127.0.0.1:6379>, @timeout=10000000>, @buffer={}>
irb(main):003:0> Ohm.redis.call "SET", "Foo", "Bar"
IO::EWOULDBLOCKWaitReadable: A non-blocking socket operation could not be completed immediately. - read would block
        from <internal:prelude>:78:in `__read_nonblock'
        from <internal:prelude>:78:in `read_nonblock'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/hiredis-0.6.1/lib/hiredis/ruby/connection.rb:268:in `read'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/redic-1.5.0/lib/redic/client.rb:26:in `read'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/redic-1.5.0/lib/redic.rb:35:in `block in call'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/redic-1.5.0/lib/redic/client.rb:37:in `block in connect'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/redic-1.5.0/lib/redic/client.rb:36:in `synchronize'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/redic-1.5.0/lib/redic/client.rb:36:in `connect'
        from C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/redic-1.5.0/lib/redic.rb:33:in `call'
        from (irb):3
        from C:/tools/ruby24/bin/irb.cmd:19:in `<main>'
```

If I read/write using Hiredis directly, it works OK.  The problem seems to be something with the Ohm/redis/hiredis interaction.   

Any ideas?

**Comment by soveran** [comment]
I've been postponing this issue to see if I can get some insight, but as I don't have access to a Windows box I have no idea what to do. Do you know someone Windows savvy who could take a look at this issue?

**Comment by soveran** [comment]
Yes, that's a good idea. Let me know how it goes :-)

**Comment by lynnfaraday** [comment]
I was suggesting _you_ do that :)   Hiredis works just fine on its own; it's only when I try to use Ohm that there's an issue.  I was just suggesting that if you want to fix it you might reach out to the Hiredis folks for help/ideas, since it might be a problem with the way that Ohm is _using_ Hiredis.

**Comment by soveran** [comment]
@lynnfaraday Ah, sorry! I misunderstood what you said. I think we should isolate the issue and report it to the hiredis team.

Can you try to run this code?

```ruby
require "hiredis/ruby/connection"

conn = Hiredis::Ruby::Connection.new
conn.connect("127.0.0.1", "6379", 10000)
conn.write(["PING"])
p conn.read
```

Make sure you have Redis running on localhost, port `6379`.

**Comment by lynnfaraday** [comment]
Here's the output of my testing showing the different results for 

1) Using Ohm directly
2) The code you asked for
3) Using Hiredis through IRB

Since Hiredis is successful in IRB but not in a ruby script running the exact same commands, it might actually be a Hiredis issue.  I'll leave that between you and them :)

[ohm.txt](https://github.com/soveran/ohm/files/2818088/ohm.txt)

**Comment by soveran** [comment]
Yes, I guess you are talking about this issue: https://github.com/redis/hiredis-rb/issues/32

Indeed the C extension is not supported, but the pure Ruby version should work. What is needed is someone willing to put the work and fix any errors, and that person most likely should have access to Windows. For me, the nature of open source is that each will try to solve their problem and share the solution with others in the same situation. If you can fix the pure Ruby version of hiredis and share it you could be helping a lot of people. If you don't have the ability or time to do it, you can still help in other ways, like reporting the issue and trying to find people with the knowledge and the time to work on it.

**Comment by lynnfaraday** [comment]
There are actually a half-dozen references in issues and StackOverflow questions about hiredis not being supported on Windows.

Nevertheless, I copied my report over to an issue on hiredis-rb.  I expect they're going to reiterate that Windows is not supported, but I could be happily surprised. 

Incidentally, the redis-rb library works just fine.  If you wanted to make Ohm use that (perhaps as a configurable option) instead of hiredis, that's an option.  I wouldn't worry about it too much though.  Redis isn't very widely-used on Windows so I suspect this problem is an edge case.

**Comment by soveran** [comment]
Thanks a lot for reporting the issue, I'll get the notifications. I will investigate a bit if I find some time, I'm quite busy lately.
