### ISSUE TITLE
best practice on how to deal with class/attribute changes

### ISSUE THREAD

**Issue by joker-777** [soveran/ohm#70]
Hi

Could you recommend how to deal best with changes on an ohm class once you have data running in productoin.

For example changing the class name, name/type of attribute.

In our example we wanna change an attribute to an counter.

Thans in advance

Johannes

**Comment by hackeron** [comment]
```
agent(prod)> Ohm.redis.smembers
NoMethodError: undefined method `smembers' for #<Redic:0x000000063ef8e0>
```
Any ideas?

**Comment by soveran** [comment]
Hello @hackeron, you can send commands to Redis with the `call` method on the `Redic` instance:

```ruby
Ohm.redis.call("SMEMBERS", "some_key")
```

You can read more about Redic here: https://github.com/amakawa/redic
