### ISSUE TITLE
Connection pooling

### ISSUE THREAD

**Issue by joseairosa** [soveran/ohm#89]
Hi @cyx and @soveran,

A couple of days ago I noticed that our redis server was running out of available connections when our API was being heavily used (we had the configuration set to provide 4000 connections).

After some careful investigation I detected where the problem was coming from.

``` ruby
puts "Connected clients = #{Ohm.redis.info['connected_clients']}"
#=> Connected clients = 135

20.times { |i| Thread.new { a=SomeModel.all[1] } }
sleep 1

puts "Connected clients = #{Ohm.redis.info['connected_clients']}"
#=> Connected clients = 155

20.times { |i| a=SomeModel.all[1] }

puts "Connected clients = #{Ohm.redis.info['connected_clients']}"
#=> Connected clients = 155
```

Basically every time we would run any threaded request a new connection would be started , thus exhausting our connection limit.

I've came up with the following solution and I would like your input on it.

``` ruby
require 'connection_pool'

REDIS_CONNECTION_POOL = ConnectionPool.new(:size => 5, :timeout => 5) {
  Redis.connect(
    :host => REDIS_CONFIG['host'],
    :port => REDIS_CONFIG['port'],
    :db => REDIS_CONFIG['db'],
    :password => REDIS_CONFIG['password'],
    :timeout => REDIS_CONFIG['timeout'],
    :thread_safe => true
  )
}

module Ohm
  class Connection
    def redis
      threaded[context] ||= REDIS_CONNECTION_POOL.with { |conn| conn }
    end
  end
end

Ohm.connect
```

After this the output was:

``` ruby
puts "Connected clients = #{Ohm.redis.info['connected_clients']}"
#=> Connected clients = 6

20.times { |i| Thread.new { a=SomeModel.all[1] } }
sleep 1

puts "Connected clients = #{Ohm.redis.info['connected_clients']}"
#=> Connected clients = 6

20.times { |i| a=SomeModel.all[1] }

puts "Connected clients = #{Ohm.redis.info['connected_clients']}"
#=> Connected clients = 6
```

What do you think about this and is this a good approach?

Thanks!

**Comment by scalp42** [comment]
@joseairosa any chance you could share some code using Ohm with redis-rb ? Reason I'm asking is that I keep seeing this error #214 

Thanks in advance for the help!

**Comment by soveran** [comment]
@scalp42 Did you run into any issues using Redic instead of redis-rb? I'd like to investigate what to do for your use case.

**Comment by scalp42** [comment]
@soveran thanks for the feedback, I switched to using Redic as you mentioned in https://github.com/soveran/ohm/issues/214#issuecomment-250089076 as I could not make it work with redis-rb.

I'm trying to figure how to convert specs for redis-rb to Redic using [fakeredis](https://github.com/guilleiguaran/fakeredis) for example:

```ruby
def redis
  @redis ||= Redis.new(db: 0, timeout: 2.0, driver: Redis::Connection::Memory)
end
``` 

I feel there's a strong assumption that you need to have a Redis instance running to write specs. I understand the idea behind Redis being easy to install etc, but I think it's unfortunate that you have to touch your local database to get tests running (Docker mitigate some of it and yes, you can also use a different database within Redis or running multiple Redis on different ports etc).

I haven't tested other gems yet like [rack-throttle][https://github.com/dryruby/rack-throttle] or [rack-attack](https://github.com/kickstarter/rack-attack) as I'm porting some code over to Ohm so "discovering-as-I-write" issues if it makes sense.

Thanks again for answering! 😄
